### ISSUE TITLE
Nested object in form

### ISSUE THREAD

**Issue by muspelheim** [codete/FormGeneratorBundle#18]
Hello, if i had nested objects in my model, can i generate form with your lib?

**Comment by malarzm** [comment]
Hi! Out of the box solution is pending fixes (#13) but it is possible to do such thing on one's own

**Comment by malarzm** [comment]
@muspelheim I'm happy to say that #13 was merged and version 1.1.0 is already available, here's link to part of readme referring to embedded objects: https://github.com/codete/FormGeneratorBundle#embed-forms
