### ISSUE TITLE
Request change createFormBuilder to allow options array to disable csrf_protection for specific forms

### ISSUE THREAD

**Issue by dbollaer** [codete/FormGeneratorBundle#21]
Hello,

I was wondering if you change this codes to allow options to be passed using the form builder.
It would allow me to disable csrf_protection when needed.

```php
     * Creates FormBuilder and populates it.
     *
     * @param object $model data object
     * @param string $form view to generate
     * @param array $context
     * @param array $options
     * @return FormBuilderInterface
     */
    public function createFormBuilder($model, $form = 'default', $context = [], $options=[])
    {
        $fb = $this->formFactory->createBuilder(FieldTypeMapper::map('form'), $model, $options);

        $this->populateFormBuilder($fb, $model, $form, $context);
        return $fb;
    }
```

It worked for me locally. If you want I can make a pull request. If their guidelines for me to follow please provide me a link.

Thank you in advance. 
Danny

**Comment by malarzm** [comment]
@dbollaer thanks for the proposition! I'll gladly accept such PR, just please adjust `createNamedFormBuilder` along and it would be great if you could add a test for that

**Comment by dbollaer** [comment]
@malarzm Thank you for your quick and helpful responses. I will be closing this comment and look forward to your next release :+1:
